<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Gender Pay Gap Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GPG_files/libs/clipboard/clipboard.min.js"></script>
<script src="GPG_files/libs/quarto-html/quarto.js"></script>
<script src="GPG_files/libs/quarto-html/popper.min.js"></script>
<script src="GPG_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GPG_files/libs/quarto-html/anchor.min.js"></script>
<link href="GPG_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GPG_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GPG_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GPG_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GPG_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Gender Pay Gap Methods</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="background-the-push-for-pay-transparency" class="level1">
<h1>Background: The Push for Pay Transparency</h1>
<p>In today’s workplace, Diversity, Equity, and Inclusion (<strong>DEI</strong>) go beyond just policies; they’re about <strong>ensuring everyone is treated and compensated fairly, regardless of gender, race, or any other protected characteristic</strong>. One of the key indicator of fair compensation is the gender pay gap (GPG), which aims at identifying differences in average pay between men and women. <strong>With recent directives like the upcoming EU pay transparency regulation, companies are increasingly required to report pay data</strong>, making GPG a critical topic for HR and analytics teams.</p>
<p>More companies are now reporting their GPGs, and with these new laws, most will soon be publisihin their numbers in yearly reports disclosing them to the public. It is therefore paramounts that the GPG is accurately estimated to avoid reputational issues and establish credibility. Traditionally, this analysis might have been handled by finance teams, but as People Analytics reach grows, data experts in HR are stepping-in to GPG reporting. However, <strong>calculating and interpreting GPG can be challenging</strong>, as it involves many factors that require careful consideration.</p>
<p>In this post, <strong>we’ll cover key metrics that help HR teams assess GPG and discuss how certain analytical choices can impact the results</strong>. Plus, I’ll share some code to make implementing these calculations straightforward for your team.</p>
</section>
<section id="key-metrics-for-gender-pay-gap-reporting" class="level1">
<h1>Key Metrics for Gender Pay Gap Reporting</h1>
<p>When it comes to gender pay gap (GPG), two main metrics are often reported: the Unadjusted and Adjusted Gender Pay Gap.</p>
<ul>
<li>The <strong>Unadjusted Gender Pay Gap (UGPG)</strong> measures the difference in average pay between all male and female employees, presented as a percentage of average male pay. UGPG is a high-level metric, reflecting overall pay differences without considering job type, experience, or role.</li>
<li>The <strong>Adjusted Gender Pay Gap (AGPG)</strong> digs a bit deeper. AGPG focuses on average difference in pay between men and women accounting for factors like role, experience, and other structural differences. The goal is to provide a more direct comparison of pay between men and women in similar positions.</li>
</ul>
<p>Determining an AGPG can be tricky, though, since <strong>deciding what qualifies as “comparable positions” and which factors should be “adjusted for” can vary between companies and contexts</strong>. Questions like <em>“What defines a comparable position?”</em> and <em>“How should we adjust for structural differences?”</em> are crucial to get accurate and meaningful GPG results. Further, while the UGPG is more explicitely defined in directives (cite EU directive), there is no consensus around how to estimate the AGPG given the methodological intricacies involved in determinging it.</p>
<p>In the following sections, I’ll <strong>break down these metrics step-by-step and include code examples you can use to start calculating GPG metrics in your organization</strong>.</p>
</section>
<section id="a-concrete-gpg-analysis-example" class="level1">
<h1>A concrete GPG analysis example</h1>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>For this post, I will be using the <a href="'https://www.kaggle.com/datasets/nilimajauhari/glassdoor-analyze-gender-pay-gap'">Glassdoor Gender Pay Gap data from Kaggle</a></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"Glassdoor Gender Pay Gap.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df) ; <span class="fu">nrow</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             JobTitle Gender Age PerfEval Education           Dept Seniority
1    Graphic Designer Female  18        5   College     Operations         2
2   Software Engineer   Male  21        5   College     Management         5
3 Warehouse Associate Female  19        4       PhD Administration         5
4   Software Engineer   Male  20        5   Masters          Sales         4
5    Graphic Designer   Male  26        5   Masters    Engineering         5
6                  IT Female  20        5       PhD     Operations         4
  BasePay Bonus
1   42363  9938
2  108476 11128
3   90208  9268
4  108080 10154
5   99464  9319
6   70890 10126</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000</code></pre>
</div>
</div>
<p>As we can see this data set contains 1000 individual records of salary, bonus, job title etc.</p>
</section>
</section>
<section id="data-exploration" class="level1">
<h1>Data Exploration</h1>
<p>Before diving into calculating the UGPG and AGPG, let’s have a look at the data characteristics broken down by gender.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="GPG_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
<p>On the diagonal of this plot grid we can see the distributions for base pay age, performance, sentiority and education. On the off-grid plots, we can see the joint plots. Gender differencs in age, performance evluation, seniority and education seem to indicate that the two groups may not be fully comparable. However, for now we will ignore this observation, which we will address later.</p>
<section id="unadjusted-gender-pay-gap" class="level2">
<h2 class="anchored" data-anchor-id="unadjusted-gender-pay-gap">Unadjusted Gender Pay Gap</h2>
<p>The first step in analyzing the GPG would be calculating the average difference in pay between man and women, also called the Unadjusted Gender Pay gap. In our case we will be calculating this metric following the definition above which is <span class="math display">\[
\text{UGPG} = \frac{\text{Avg. male earnings} - \text{Avg. female earnings}}{\text{Avg. male earnings}} \times 100\%
\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>avg_pay_men <span class="ot">=</span> <span class="fu">mean</span>(df[df[<span class="st">'Gender'</span>] <span class="sc">==</span> <span class="st">'Male'</span>, <span class="st">'BasePay'</span>])</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>avg_pay_women <span class="ot">=</span> <span class="fu">mean</span>(df[df[<span class="st">'Gender'</span>] <span class="sc">==</span> <span class="st">'Female'</span>, <span class="st">'BasePay'</span>])</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>GPG <span class="ot">=</span> <span class="fu">round</span>(((avg_pay_men<span class="sc">-</span>avg_pay_women)<span class="sc">/</span>avg_pay_men)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"The Unadjusted Gender Pay Gap is = "</span>, GPG, <span class="st">"%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The Unadjusted Gender Pay Gap is = 8.65%"</code></pre>
</div>
</div>
<p>As we can see, the UGPG seems to be -8.65% meaning that women earn, on average, 8.65% less than men. However, this metric is quite rough as it does not take into account other characteristics that may be relevant to someone’s pay, such as their job title, years of experience etc. The UGPG can be seen as a rough estimate of the GPG, and that is why more refined metrics, such as the AGPG are also reported.</p>
</section>
</section>
<section id="adjusted-gpg" class="level1">
<h1>Adjusted GPG</h1>
<p>The AGPG can be seen as a refined UGPG, where individual characteristics are taken into account when comparing men and women differences in salary.</p>
<section id="oaxaca-blinder" class="level2">
<h2 class="anchored" data-anchor-id="oaxaca-blinder">Oaxaca Blinder</h2>
<p>A typical approach to calculate the AGPG is the Oaxaca-Blinder method. This approach is a statistical method used to decompose pay differences into explainable factors (differences in education or experience) and unexplainable factors (someone’s gender). This method allows for a clearer understanding of how much of the pay gap can be explained by measurable differences versus systemic inequalities.</p>
<p>Let’s see how we can apply the Oaxaca-Blinder method to our dataset</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#library(oaxaca)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(OaxacaBlinder)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Salary variables are often skewed so we first log transform it to make it approximately normal</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>BasePay_log <span class="ot">=</span> <span class="fu">log</span>(df_clean<span class="sc">$</span>BasePay)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Oaxaca-blinder requires to have the "grouping" variable dummified, here we have Men coded as 0 and Women coded as 1</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>Gender_fac <span class="ot">=</span> <span class="fu">ifelse</span>(df_clean<span class="sc">$</span>Gender <span class="sc">==</span> <span class="st">"Male"</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">#oaxaca.results = oaxaca(BasePay_log ~ Age + PerfEval + Education + Seniority + Dept + JobTitle | Gender_fac, data = df_clean)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>twofold <span class="ot">=</span> <span class="fu">OaxacaBlinderDecomp</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> BasePay_log <span class="sc">~</span> Age <span class="sc">+</span> PerfEval <span class="sc">+</span> Education <span class="sc">+</span> Seniority <span class="sc">+</span> Dept <span class="sc">+</span> JobTitle <span class="sc">|</span> Gender_fac,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_clean,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"twofold"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">baseline_invariant =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_bootstraps =</span> <span class="dv">100</span> <span class="co">#internal bootstrapping for explained and unexplained coefficients</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co">#AGPG = round(((oaxaca.results$y$y.A - oaxaca.results$y$y.B)/oaxaca.results$y$y.A)*100,2)</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co">#paste0("The AGPG estimated through Oaxaca-Blinder = ", -1*AGPG, "%")</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(twofold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Oaxaca Blinder Decomposition model
----------------------------------
Type: twofold
Formula: BasePay_log ~ Age + PerfEval + Education + Seniority + Dept +      JobTitle | Gender_fac
Data: df_clean

Descriptives
                n    %n mean(BasePay_log)
Gender_fac==0 532 53.2%             11.46
Gender_fac==1 468 46.8%             11.37

Gap: 0.1
% Diff: 0.83%
              coefficient   % of gap          se         2.5%      97.5%
explained            0.09      91.1% 0.017168956  0.049046070 0.11344079
unexplained          0.01       8.9% 0.007146303 -0.006234230 0.01999189
unexplained_a        0.00       4.2% 0.003347297 -0.002934171 0.00935835
unexplained_b        0.00       4.7% 0.003807716 -0.003300059 0.01099998</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>twofold<span class="sc">$</span>gaps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$gap
[1] 0.09531562

$pct_gap
[1] 0.008315925

$EY_a
[1] 11.46182

$EY_b
[1] 11.3665</code></pre>
</div>
</div>
<p>What we can see from the Oaxaca-blinder results is that the Gender pay gap amounts to 0.83%, indicating that women earn, on average, 0.83% less than men.</p>
<p>An issue that is often overlooked by the Oaxaca-Blinder is that of group comparability. For instance, we coud have Male in their early thirties with a specific job function (e.g., sales associate) and seniority but not female counterparts, and vice versa. This is a common situation since female may tend to concentrate in certain occupations for which specific skills are more likely to be found, whereas male may concentrate in other occupations. This issue is also known as “common support” issue, which is crucially overlooked by the Oaxaca-blinder. In fact, since in the Oaxaca-blinder model there are no restrictions imposed on estimating earnings for male and female with comparable characteristics <a href="'https://www.iza.org/publications/dp/981/matching-as-a-tool-to-decompose-wage-g'">Ñopo, 2004</a>.</p>
</section>
<section id="ipwra" class="level2">
<h2 class="anchored" data-anchor-id="ipwra">IPWRA</h2>
<p>A procedure that allows us to account for group comparability is that of Inverse Probability Weighting Regression Adjustement (IPW).</p>
<p>IPWRA uses two steps: - Calculate weights based on the probability of being female (using a model such as probit or logit). - Fit a weighted regression model within each group and estimate the treatment effect on the outcome.</p>
<p>In other words, the idea is to assign weights to observation in our sample, by giving larger weights to observation that are similar to each other, and smaller weights to the rest. This way we can introduce some adjustements to increase men and women comparability.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary packages</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>formula_ipw <span class="ot">=</span> <span class="st">'Gender_fac ~ Age + PerfEval + Education + Seniority + Dept + JobTitle'</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>formula_lm <span class="ot">=</span> <span class="st">'BasePay_log ~  Gender_fac + Age + PerfEval + Education + Seniority + Dept + JobTitle'</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3112024</span>) <span class="co">#for reproducibility purposes</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the IPWRA estimation function. Here we run it using a bootstrap approach to obtain CIs and compare the estimates afterwards.</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>ipwra_estimation <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Subset data based on resampled indices</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  df_resampled <span class="ot">&lt;-</span> data[indices, ]</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Fit a propensity score model to obtain IP weights</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  propensity_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(formula_ipw,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">'probit'</span>),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> df_resampled)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate IP weights based on propensity scores</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  ip_weights <span class="ot">&lt;-</span> <span class="fu">predict</span>(propensity_model, df_resampled, <span class="at">type =</span> <span class="st">'response'</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  outcome <span class="ot">&lt;-</span> df_resampled<span class="sc">$</span>Gender_fac</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  df_resampled<span class="sc">$</span>ipw_weights <span class="ot">&lt;-</span> (outcome <span class="sc">/</span> ip_weights) <span class="sc">+</span> ((<span class="dv">1</span> <span class="sc">-</span> outcome) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> ip_weights))</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Fit weighted regression models for each gender group</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>  model_female <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_lm,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> df_resampled, <span class="at">subset =</span> (Gender_fac <span class="sc">==</span> <span class="dv">1</span>), <span class="at">weights =</span> ipw_weights)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  model_male <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_lm,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> df_resampled, <span class="at">subset =</span> (Gender_fac <span class="sc">==</span> <span class="dv">0</span>), <span class="at">weights =</span> ipw_weights)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Predict the adjusted salaries and calculate the average treatment effect (ATE)</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>  df_resampled<span class="sc">$</span>predicted_female <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_female, <span class="at">newdata =</span> df_resampled, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>  df_resampled<span class="sc">$</span>predicted_male <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_male, <span class="at">newdata =</span> df_resampled, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>  mean_predicted_female <span class="ot">&lt;-</span> <span class="fu">mean</span>(df_resampled<span class="sc">$</span>predicted_female, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>  mean_predicted_male <span class="ot">&lt;-</span> <span class="fu">mean</span>(df_resampled<span class="sc">$</span>predicted_male, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate the GPG estimate</span></span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>  ATE <span class="ot">&lt;-</span> <span class="fu">exp</span>(mean_predicted_female) <span class="sc">-</span> <span class="fu">exp</span>(mean_predicted_male)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>  ATE_percentage <span class="ot">&lt;-</span> (ATE <span class="sc">/</span> <span class="fu">exp</span>(mean_predicted_male)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(ATE_percentage)</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the bootstrap with 1000 resamples</span></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>bootstrap_results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> df_clean, <span class="at">statistic =</span> ipwra_estimation, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the 95% confidence interval</span></span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(bootstrap_results, <span class="at">type =</span> <span class="st">"perc"</span>)</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The estimated Average Treatment Effect (ATE) of being female on wage is:"</span>, </span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="fu">mean</span>(bootstrap_results<span class="sc">$</span>t), <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The estimated Average Treatment Effect (ATE) of being female on wage is: -1.45 %</code></pre>
</div>
</div>
<p>After weighting and adjusting for relevant factors, the estimated pay gap is approximately 1.45%, which is quite different from the Oaxaca-Blinder method. IPWRA, however, is not a cure-all approach and other methodologies exist to improve group’s comparability. One of the most known one is that of matching.</p>
</section>
<section id="matching" class="level2">
<h2 class="anchored" data-anchor-id="matching">Matching</h2>
<p>Matching is another approach to address common support issues. Unlike IPWRA, matching creates pairs or groups of individuals with similar characteristics across treatment groups (e.g., male and female) and then compares them directly. Here, we use full matching to ensure each observation finds the closest comparable counterpart.</p>
<p>To do that, we first create a matched sample.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Run the full-matching algorithm</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>match <span class="ot">=</span> <span class="fu">matchit</span>(<span class="fu">as.formula</span>(formula_ipw), </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">'full'</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> df_clean,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">distance =</span> <span class="st">'glm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then, we evaluate the similarity between the samples by looking at the standardized mean differences for each covariate between men and women. A well-balanced sample would reasult in mean differences close to 0.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking balance after cem matching</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(match, <span class="at">un =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = as.formula(formula_ipw), data = df_clean, method = "full", 
    distance = "glm")

Summary of Balance for Matched Data:
                            Means Treated Means Control Std. Mean Diff.
distance                           0.5735        0.5730          0.0025
Age                               41.8291       41.4478          0.0276
PerfEval                           2.9359        3.0069         -0.0495
EducationCollege                   0.2628        0.2321          0.0698
EducationHigh School               0.2821        0.2928         -0.0239
EducationMasters                   0.2286        0.2290         -0.0008
EducationPhD                       0.2265        0.2461         -0.0469
Seniority                          3.0128        3.1115         -0.0710
DeptAdministration                 0.2030        0.3030         -0.2486
DeptEngineering                    0.1902        0.1806          0.0244
DeptManagement                     0.1859        0.1910         -0.0132
DeptOperations                     0.2051        0.1936          0.0285
DeptSales                          0.2158        0.1318          0.2042
JobTitleData Scientist             0.1132        0.1145         -0.0039
JobTitleDriver                     0.0983        0.0970          0.0043
JobTitleFinancial Analyst          0.1047        0.0959          0.0288
JobTitleGraphic Designer           0.1026        0.0929          0.0318
JobTitleIT                         0.1068        0.0902          0.0540
JobTitleManager                    0.0385        0.0385          0.0000
JobTitleMarketing Associate        0.2286        0.2286          0.0000
JobTitleSales Associate            0.0919        0.0956         -0.0127
JobTitleSoftware Engineer          0.0171        0.0171          0.0000
JobTitleWarehouse Associate        0.0983        0.1298         -0.1059
                            Var. Ratio eCDF Mean eCDF Max Std. Pair Dist.
distance                        0.9943    0.0038   0.0662          0.0108
Age                             0.9836    0.0148   0.0472          1.1090
PerfEval                        1.1398    0.0361   0.0772          0.7794
EducationCollege                     .    0.0307   0.0307          0.6546
EducationHigh School                 .    0.0108   0.0108          0.8050
EducationMasters                     .    0.0003   0.0003          0.6494
EducationPhD                         .    0.0196   0.0196          0.8220
Seniority                       1.1428    0.0408   0.0655          1.1060
DeptAdministration                   .    0.1000   0.1000          0.8102
DeptEngineering                      .    0.0096   0.0096          0.8054
DeptManagement                       .    0.0051   0.0051          0.8556
DeptOperations                       .    0.0115   0.0115          0.8417
DeptSales                            .    0.0840   0.0840          0.7275
JobTitleData Scientist               .    0.0012   0.0012          0.5031
JobTitleDriver                       .    0.0013   0.0013          0.4651
JobTitleFinancial Analyst            .    0.0088   0.0088          0.4751
JobTitleGraphic Designer             .    0.0097   0.0097          0.4057
JobTitleIT                           .    0.0167   0.0167          0.4709
JobTitleManager                      .    0.0000   0.0000          0.0000
JobTitleMarketing Associate          .    0.0000   0.0000          0.0000
JobTitleSales Associate              .    0.0037   0.0037          0.4648
JobTitleSoftware Engineer            .    0.0000   0.0000          0.0000
JobTitleWarehouse Associate          .    0.0315   0.0315          0.5309

Sample Sizes:
              Control Treated
All            532.       468
Matched (ESS)   68.76     468
Matched        532.       468
Unmatched        0.         0
Discarded        0.         0</code></pre>
</div>
</div>
<p>As we can see, in this example, for some groups men and women are not fully comparable. For instance, we observe a negative and positive mean difference between men and women in the Administration Department and Sales Department, respectively. This may not be surprising, since women are more ofte found in administration positions whereas men in sales positions (cite).</p>
<p>Finally, we calculate the Adjusted GPG on this matched sample.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_out <span class="ot">=</span> <span class="fu">match.data</span>(match)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Estimate the Treatment Effect with Weights obtained from matching</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>mod_matched <span class="ot">&lt;-</span> <span class="fu">lm</span>(BasePay_log <span class="sc">~</span>  Gender_fac, <span class="at">data =</span> df_out, <span class="at">weights =</span> weights)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Convert the Effect from Log Wage to Percentage</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the coefficient for female</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>female_coef <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod_matched)[<span class="st">"Gender_fac"</span>]</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>ATE_percentage <span class="ot">&lt;-</span> (<span class="fu">exp</span>(female_coef) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The estimated AGPG using matching is:"</span>, <span class="fu">round</span>(ATE_percentage, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The estimated AGPG using matching is: -2.55 %</code></pre>
</div>
</div>
<p>The matching approach estimates an adjusted gender pay gap of -2.51%, which again differs from those reported before.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>twofold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Oaxaca Blinder Decomposition model
----------------------------------
Type: twofold
Formula: BasePay_log ~ Age + PerfEval + Education + Seniority + Dept +      JobTitle | Gender_fac
Data: df_clean</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% Confidence Interval:"</span>, <span class="fu">round</span>(ci<span class="sc">$</span>percent[<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>], <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>95% Confidence Interval: -3.09 0.29 %</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod_matched)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %       97.5 %
(Intercept) 11.36855762 11.416106021
Gender_fac  -0.06058169  0.008922821</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>